"use strict";
module.exports = (sequelize, DataTypes) => {
  const Grant = sequelize.define(
    "Grant",
    {
      agency: DataTypes.STRING,
      primary: DataTypes.STRING,
      tax_id: DataTypes.STRING,
      contact: DataTypes.STRING,
      person_title: DataTypes.STRING,
      address: DataTypes.STRING,
      phone: DataTypes.STRING,
      fax: DataTypes.STRING,
      email: DataTypes.STRING,
      info: DataTypes.STRING,
      docs: DataTypes.STRING,
      title: DataTypes.STRING,
      new_or_current: DataTypes.STRING,
      funding_past: DataTypes.STRING,
      synopsis: DataTypes.STRING,
      priority: DataTypes.STRING,
      outcomes: DataTypes.STRING,
      collaborative: DataTypes.STRING,
      sources: DataTypes.STRING,
      sustainability: DataTypes.STRING,
      no_of_people: DataTypes.INTEGER,
      socio: DataTypes.STRING,
      age: DataTypes.STRING,
      gender: DataTypes.STRING,
      clients: DataTypes.STRING,
      budget: DataTypes.STRING,
      head: DataTypes.STRING,
      head_title: DataTypes.STRING,
      date: DataTypes.DATE,
      user_id: DataTypes.STRING,
      main_outcomes: DataTypes.STRING,
      describe: DataTypes.STRING,
      isAdditional: DataTypes.BOOLEAN,
      additional: DataTypes.STRING,
      signature: DataTypes.STRING,
      annual: DataTypes.BOOLEAN,
      roster: DataTypes.BOOLEAN,
      audit: DataTypes.BOOLEAN,
      proof: DataTypes.BOOLEAN,
      income: DataTypes.BOOLEAN,
      letters: DataTypes.BOOLEAN,
      score: DataTypes.INTEGER,
      comments: DataTypes.STRING,
      status: DataTypes.STRING,
      links: DataTypes.STRING,
      mission: DataTypes.STRING,
      annual_file: DataTypes.STRING,
      roster_file: DataTypes.STRING,
      audit_file: DataTypes.STRING,
      proof_file: DataTypes.STRING,
      letters_file: DataTypes.STRING,
      director: DataTypes.STRING,
      funding: DataTypes.STRING,
      implementation: DataTypes.STRING,
      rfp: DataTypes.STRING,
      zip: DataTypes.STRING,
      equity: DataTypes.STRING,
      population: DataTypes.STRING,
      budget_file: DataTypes.STRING,
      additional_file: DataTypes.STRING
    },
    {}
  );
  Grant.associate = function(models) {
    // associations can be defined here
  };
  return Grant;
};
