const user_id = localStorage.user ? JSON.parse(localStorage.user).id : null;

export const initialValues = {
  firstname: "",
  lastname: "",
  street: "",
  city: "",
  state: "",
  zip: "",
  home_phone: "",
  cell: "",
  email: "",
  birthdate: new Date(),
  learn: "",
  is_relatives: null,
  relatives: "",
  guardian1_name: "",
  guardian1_street: "",
  guardian1_city: "",
  g1_state: "",
  guardian1_zip: "",
  guardian1_occupation: "",
  guardian2_name: "",
  guardian2_street: "",
  guardian2_city: "",
  g2_state: "",
  guardian2_zip: "",
  guardian2_occupation: "",
  no_of_siblings: "",
  no_in_college: "",
  k12: "",
  live_with_parents: "",
  explain_living: "",
  years_on_job: 0,
  place_employment: "",
  plan_to_work: null,
  hours_week: null,
  school: "",
  school_address: "",
  school_year: "",
  class_rank: "",
  gpa: "",
  weighted_gpa: "",
  act: "",
  english: "",
  science: "",
  math: "",
  reading: "",
  composite: "",
  other_scores: "",
  counselor: "",
  counselor_phone: "",
  colleges_applied: "",
  college_planned: "",
  accepted_nursing: "",
  when_apply: null,
  field_of_interest: "",
  graduate_month: null,
  graduate_year: "",
  college_classes_taken: "",
  college_awarded: "",
  transcripts: null,
  acceptance: null,
  statement: null,
  recommendation: null,
  transcripts_file: "",
  acceptance_file: "",
  statement_file: "",
  recommendation_file: "",
  date: new Date(),
  signature: "",
  siblings: [],
  activities: [],
  status: "",
  score: "",
  comments: "",
  user_id,
};
